server:
  port: 8443
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
 




spring:
   datasource:
      url: jdbc:mysql://rm-bp1x0pg4z9g5d7knmno.mysql.rds.aliyuncs.com:3306/intelligent_parking?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      #url: jdbc:mysql://rm-wz9hr508e7cmm5go0lo.mysql.rds.aliyuncs.com:3306/intelligent_parking?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: xcs@2018
      tomcat:
          max-active: 20
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.cj.jdbc.Driver

    
redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000ms
#mybaties配置
mybatis:
    type-aliases-package: com.example.demo.entity
    mapper-locations: classpath*:/mapper/**.xml
    check-config-location: true
    configuration:
        map-underscore-to-camel-case: true

# 通用mapper 配置 自动生成dao层代码
mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

logging:
    path: ./log
    level:
        #控制台打印sql语句
        com.example.demo.mapper: debug



